services:
  asl_back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - asl_db
    env_file:
      - .env
    container_name: asl_back
    volumes:
      - .:/usr/src/app
    networks:
      - nestjs

  asl_db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    container_name: asl_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      nestjs:

volumes:
  postgres-data:

networks:
  nestjs:
